lamxuanthinh/Project03

- app/src/main/res/layout/fragment_login.xml
change background fragment-login
> change backgound

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/project03/adapters/HomeViewpagerAdapter.kt
- app/src/main/java/com/example/project03/fragments/categories/AccessoryFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/BaseCategoryFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/ChairFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/CupboardFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/FurnitureFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/MainCategoryFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/TableFragment.kt
- app/src/main/java/com/example/project03/fragments/shopping/HomeFragment.kt
- app/src/main/res/layout/fragment_base_caterory.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_main_category.xml
> Feature UI tab layout

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/project03/fragments/categories/MainCategory.kt
- app/src/main/res/layout/activity_shopping.xml
> Feature shopping

- app/src/main/java/com/example/project03/fragments/categories/MainCategoryFragment.kt
- app/src/main/java/com/example/project03/fragments/shopping/ProductDetailsFragment.kt
- app/src/main/java/com/example/project03/viewmodel/MainCategoryViewModel.kt
sửa lỗi import các file MainCategoryFragment.kt,ProductDetailsFragment.kt,MainCategoryViewModel.kt
> #26 fix import

- app/src/main/res/layout/cart_product_item.xml
- app/src/main/res/layout/fragment_cart.xml
> #25 Cart Fragment

- app/src/main/java/com/example/project03/adapters/CartProductAdapter.kt
- app/src/main/java/com/example/project03/firebase/FirebaseCommon.kt
- app/src/main/java/com/example/project03/viewmodel/CartViewModel.kt
- app/src/main/java/com/example/project03/viewmodel/DetailsviewModel.kt
> fix import vơi tu sai

- app/src/main/java/com/example/project03/viewmodel/CartViewModel.kt
> fix cartviewmodel

- app/src/main/java/com/example/project03/fragments/shopping/CartFragment.kt
- app/src/main/java/com/example/project03/viewmodel/CartViewModel.kt
- app/src/main/res/layout/fragment_cart.xml
> 48 cart product

- .gitignore
- .idea/deploymentTargetDropDown.xml
- app/.idea/.gitignore
- app/.idea/gradle.xml
- app/.idea/misc.xml
- app/.idea/vcs.xml
- app/build.gradle
- app/src/main/java/com/example/project03/di/AppModule.kt
- app/src/main/java/com/example/project03/fragments/settings/UserAccountFragment.kt
- app/src/main/java/com/example/project03/viewmodel/UserAccountViewMoldel.kt
- app/src/main/res/layout/fragment_user_account.xml
video 31 thiếu phần shoppinggraph do thiếu dữ liệu
> #52 Feature-User-Profile-Settings -shoppinggraph

- app/src/main/java/com/example/project03/fragments/categories/MainCategoryFragment.kt
- app/src/main/java/com/example/project03/viewmodel/MainCategoryViewModel.kt
- app/src/main/res/layout/fragment_main_category.xml
> #55 paging and queries

- app/src/main/java/com/example/project03/adapters/AddressAdapter.kt
- app/src/main/java/com/example/project03/adapters/BillingProductsAdapter.kt
- app/src/main/java/com/example/project03/data/CartProduct.kt
- app/src/main/java/com/example/project03/fragments/shopping/BillingFragment.kt
- app/src/main/java/com/example/project03/fragments/shopping/CartFragment.kt
- app/src/main/java/com/example/project03/util/HorizontalItemDecoration.kt
- app/src/main/java/com/example/project03/viewmodel/BillingViewModel.kt
- app/src/main/res/drawable/ic_add.xml
- app/src/main/res/drawable/ic_location.xml
- app/src/main/res/drawable/unselected_button_background.xml
- app/src/main/res/layout/address_rv_item.xml
- app/src/main/res/layout/billing_products_rv_item.xml
- app/src/main/res/layout/fragment_billding.xml
- app/src/main/res/navigation/shopping_graph.xml
> #46 Billing Fragment

- app/.idea/workspace.xml
- app/src/main/java/com/example/project03/data/Category.kt
- app/src/main/java/com/example/project03/fragments/categories/AccessoryFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/BaseCategoryFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/ChairFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/CupboardFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/FurnitureFragment.kt
- app/src/main/java/com/example/project03/fragments/categories/TableFragment.kt
- app/src/main/java/com/example/project03/viewmodel/CategoryViewModel.kt
- app/src/main/java/com/example/project03/viewmodel/factory/BaseCategoryViewModelFactoryFactory.kt
- app/src/main/res/layout/fragment_base_caterory.xml
video 20 Feature-Finish-Categories
> #59 Feature-Finish-Categories

- Admin/app/build.gradle
- Admin/app/google-services.json
- Admin/app/src/main/java/com/example/productsadder/MainActivity.kt
- Admin/app/src/main/java/com/example/productsadder/Product.kt
- Admin/app/src/main/res/layout/activity_main.xml
- Admin/build.gradle
> #61 completed admin

- Admin/.idea/deploymentTargetDropDown.xml
- app/src/main/java/com/example/project03/di/AppModule.kt
- app/src/main/java/com/example/project03/fragments/categories/MainCategoryFragment.kt
- app/src/main/java/com/example/project03/viewmodel/CategoryViewModel.kt
- app/src/main/java/com/example/project03/viewmodel/MainCategoryViewModel.kt
- app/src/main/res/layout/fragment_base_caterory.xml
> Fix layout fragment_base_caterory

- app/src/main/java/com/example/project03/data/order/Order.kt
- app/src/main/java/com/example/project03/data/order/OrderStatus.kt
- app/src/main/java/com/example/project03/viewmodel/BillingViewModel.kt
>  Sửa package

- app/src/main/java/com/example/project03/adapters/OrdersAdapter.kt
- app/src/main/java/com/example/project03/data/order/Order.kt
- app/src/main/java/com/example/project03/data/order/OrderStatus.kt
- app/src/main/java/com/example/project03/fragments/settings/OrdersFragment.kt
- app/src/main/java/com/example/project03/viewmodel/OrdersViewModel.kt
- app/src/main/res/drawable/ic_arrow.xml
- app/src/main/res/layout/fragment_orders.xml
- app/src/main/res/layout/order_item.xml
- app/src/main/res/navigation/shopping_graph.xml
- app/src/main/res/values/styles.xml
> #32 Get All Orders

- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/example/project03/data/Category.kt
- app/src/main/java/com/example/project03/fragments/categories/ClothesFragment.kt
- app/src/main/java/com/example/project03/fragments/shopping/HomeFragment.kt
- app/src/main/res/layout/fragment_main_category.xml
- app/src/main/res/layout/product_rv_item.xml
> fix layout

- app/src/main/res/drawable/ic_favorite.xml
- app/src/main/res/layout/fragment_account_options.xml
- app/src/main/res/layout/fragment_base_caterory.xml
- app/src/main/res/layout/fragment_login.xml
- app/src/main/res/layout/fragment_main_category.xml
- app/src/main/res/layout/fragment_register.xml
- app/src/main/res/layout/product_rv_item.xml
> update layout 2

- app/src/main/java/com/example/project03/adapters/BestDealsAdapter.kt
- app/src/main/java/com/example/project03/adapters/BestProductsAdapter.kt
- app/src/main/java/com/example/project03/adapters/SpecialProductsAdapter.kt
- app/src/main/java/com/example/project03/fragments/categories/MainCategoryFragment.kt
- app/src/main/java/com/example/project03/fragments/shopping/HomeFragment.kt
- app/src/main/java/com/example/project03/viewmodel/MainCategoryViewModel.kt
- app/src/main/res/layout/fragment_account_options.xml
- app/src/main/res/layout/fragment_introduction.xml
- app/src/main/res/layout/special_rv_item.xml
- app/src/main/res/values/strings.xml
layout and price @lamxuanthinh
> layout and price

- app/src/main/java/com/example/project03/fragments/shopping/HomeFragment.kt
- app/src/main/java/com/example/project03/fragments/shopping/SearchFragment.kt
- app/src/main/java/com/example/project03/viewmodel/SearchViewModel.kt
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/navigation/shopping_graph.xml
> add search

- app/src/main/res/drawable/baseline_add_location_alt_24.xml
- app/src/main/res/drawable/baseline_assured_workload_24.xml
- app/src/main/res/drawable/baseline_border_color_24.xml
- app/src/main/res/drawable/baseline_location_city_24.xml
- app/src/main/res/drawable/baseline_phone_24.xml
- app/src/main/res/drawable/person.xml
- app/src/main/res/layout/fragment_address.xml
- app/src/main/res/layout/fragment_billding.xml
> layout address
